pragma Singleton
import QtQuick

QtObject {
    readonly property string transparent: "transparent"
    readonly property string bgDim: "#232A2E"
    readonly property string fg: "#D3C6AA"
    readonly property string bg0: "#2D353B"
    readonly property string bg1: "#343F44"
    readonly property string bg2: "#3D484D"
    readonly property string bg3: "#475258"
    readonly property string bg4: "#4F585E"
    readonly property string bg5: "#56635f"
    readonly property string bgVisual: "#543A48"
    readonly property string bgRed: "#514045"
    readonly property string bgGreen: "#425047"
    readonly property string bgBlue: "#3A515D"
    readonly property string bgYellow: "#4D4C43"
    readonly property string orange: "#E69875"
    readonly property string yellow: "#DBBC7F"
    readonly property string green: "#A7C080"
    readonly property string aqua: "#83C092"
    readonly property string blue: "#7FBBB3"
    readonly property string purple: "#D699B6"
    readonly property string grey0: "#7A8478"
    readonly property string grey1: "#859289"
    readonly property string grey2: "#9DA9A0"
    readonly property string statusline1: "#A7C080"
    readonly property string statusline2: "#D3C6AA"
    readonly property string statusline3: "#E67E80"
}
