import Quickshell
import Quickshell.Widgets
import Quickshell.Io
import Quickshell.Hyprland

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

import qs.Constants
import qs.Components

PanelWindow {
    id: root

    visible: false
    anchors.right: true
    margins.right: Styles.marginLg
    exclusionMode: ExclusionMode.Ignore

    implicitWidth: 700
    implicitHeight: 900
    color: "transparent"

    property var clipboard: []
    property string currentClipboard: ""

    GlobalShortcut {
        name: 'clipboard'
        onPressed: {
            cliphistList.running = true;
            root.visible = !root.visible;
            grab.active = true;
            base.focus = true;
        }
    }

    HyprlandFocusGrab {
        id: grab
        windows: [root]
        onCleared: root.visible = false
    }

    Process {
        id: cliphistList
        // Command generated by ai to convert cliphist list to an array.
        command: ["sh", "-c", "cliphist list | while IFS= read -r line; do echo \"$line\" | cliphist decode | jq -Rs .; done | jq -s ."]
        property var buffer: []
        property string jsonOutput: ""
        onStarted: {
            buffer = [];
            jsonOutput = "";
        }
        stdout: SplitParser {
            onRead: line => cliphistList.jsonOutput += line
        }
        onExited: {
            try {
                this.buffer = JSON.parse(this.jsonOutput);
                root.clipboard = this.buffer;
            } catch (e) {
                console.error("Failed to parse clipboard JSON:", e);
                root.clipboard = [];
            }
        }
    }

    Rectangle {
        id: base

        anchors.fill: parent

        color: Colors.bgDim
        radius: Styles.radiusSm

        property int selectedEntryIndex: 0

        Keys.onPressed: event => {
            if ([Qt.Key_Escape, Qt.Key_Q].includes(event.key)) {
                root.visible = false;
                return;
            } else if ([Qt.Key_Down, Qt.Key_J].includes(event.key)) {
                clipboardItems.incrementCurrentIndex();
            } else if ([Qt.Key_Up, Qt.Key_K].includes(event.key)) {
                clipboardItems.decrementCurrentIndex();
            } else if ([Qt.Key_Return, Qt.Key_Enter].includes(event.key)) {
                clipboardItems.currentItem.clicked(null);
                root.visible = false;
                return;
            } else if ([Qt.Key_G].includes(event.key)) {
                clipboardItems.currentIndex = 0;
            }
            clipboardItems.positionViewAtIndex(clipboardItems.currentIndex, ListView.Contain);
        }

        ColumnLayout {
            id: mainContent
            anchors.fill: parent

            Rectangle {
                id: currentClipboardDisplay
                z: 1

                Layout.fillWidth: true
                Layout.margins: Styles.marginSm

                Layout.preferredHeight: currentClipboardText.implicitHeight + Styles.marginSm * 2
                color: Colors.bgRed
                radius: Styles.radiusMd

                TextStyled {
                    id: currentClipboardText
                    text: " " + root.clipboard[0]
                    wrapMode: Text.WrapAtWordBoundaryOrAnywhere
                    anchors.centerIn: parent
                    width: parent.width - Styles.marginSm * 2
                    anchors.margins: Styles.marginSm
                }
            }

            ClippingRectangle {
                id: rect
                Layout.fillHeight: true
                Layout.fillWidth: true
                Layout.margins: Styles.marginSm
                color: "transparent"
                radius: Styles.radiusMd

                ListView {
                    id: clipboardItems
                    anchors.fill: parent
                    spacing: Styles.marginSm
                    model: root.clipboard
                    delegate: ButtonStyled {
                        id: button

                        implicitHeight: clipboardItemContent.implicitHeight
                        implicitWidth: rect.width
                        radius: Styles.radiusMd

                        defaultColor: Colors.bg0

                        focusedColor: Colors.bgGreen

                        isFocused: ListView.isCurrentItem

                        ColumnLayout {
                            id: clipboardItemContent
                            anchors {
                                top: parent.top
                                left: parent.left
                                right: parent.right
                            }

                            property string keyValue: String(root.clipboard.length - index) // Equation is to flip from 0 - N to N - 0
                            property string clipboardValue: modelData

                            Rectangle {
                                id: clipboardItemKey
                                Layout.preferredWidth: 80
                                implicitHeight: 20
                                color: Colors.orange
                                radius: Styles.radiusSm
                                TextStyled {
                                    id: clipboardItemKeyText
                                    wrapMode: Text.WrapAtWordBoundaryOrAnywhere
                                    color: Colors.bgDim
                                    anchors.centerIn: parent
                                    text: clipboardItemContent.keyValue
                                }
                            }

                            Rectangle {
                                color: Colors.bgDim
                                radius: Styles.radiusMd

                                Layout.fillWidth: true
                                Layout.preferredHeight: clipboardText.implicitHeight + Styles.marginSm * 2
                                Layout.margins: Styles.marginSm

                                TextStyled {
                                    id: clipboardText
                                    wrapMode: Text.WrapAtWordBoundaryOrAnywhere
                                    width: parent.width - Styles.marginSm
                                    anchors.centerIn: parent
                                    color: Colors.blue
                                    text: clipboardItemContent.clipboardValue
                                }
                            }
                        }

                        onClicked: {
                            Quickshell.execDetached(['sh', '-c', 'printf %s "' + modelData.replace(/"/g, '\\"') + '" | wl-copy']);
                            Quickshell.execDetached(['bash', '-c', 'notify-send -a System "Clipboard Copied"']);
                            root.visible = false;
                        }
                    }
                }
            }
        }
    }
}
