# Startup
exec-once = rabbit-shell

# animations
animations:enabled = true

animation = windows, 1, 10, default, popin
animation = specialWorkspace, 1, 30, default, slidefadevert
animation = layers, 1, 4, default, slidefade

# Default Keybinds
bind = Super, Backspace, global, quickshell:powermenu
bindo = Super, Backspace, global, quickshell:lockscreen
bind = Super, Escape, global, quickshell:idleToggle
bind = Super, Space, global, quickshell:applauncher
bind = Super, M, global, quickshell:mixer
bind = Super, V, global, quickshell:clipboard
bind = Super, N, global, quickshell:notification-manager
bind = Super, E, global, quickshell:texteditor
bind = Super, D, global, quickshell:screendraw
bind = Super, T, global, quickshell:timemanager
bind = Super, slash, global, quickshell:cheatsheet
bind = Alt, Tab, global, quickshell:toplevelview

# The clipboard manager.
exec-once = wl-paste --type text --watch sh -c 'qs ipc call clip save "$(wl-paste --type text)"'
exec-once = wl-paste --type image --watch sh -c 'wl-paste > ~/Pictures/clipboard/$(date +%F-%H-%M-%S).png'
