# Default Keybinds
bind = $mainMod , Backspace, global, quickshell:powermenu
bindo = $mainMod, Backspace, global, quickshell:lockscreen
bind = $mainMod, Escape, global, quickshell:idleToggle
bind = $mainMod, Tab, global, quickshell:workspaces
bind = $mainMod, Space, global, quickshell:applauncher
bind = $mainMod, M, global, quickshell:mixer
bind = $mainMod, V, global, quickshell:clipboard
bind = $mainMod, N, global, quickshell:notification-manager
bind = Alt, Tab, global, quickshell:toplevelview

# The clipboard manager.
exec-once = wl-paste --type text --watch sh -c 'qs ipc call clip save "$(wl-paste --type text)"'
