pragma Singleton

import Quickshell
import Quickshell.Io

import QtQuick
import QtCore as QtCoreLib

Singleton {
    id: root

    property list<MonitorInfo> monitors

    function init() {
        console.log('HyprctlMonitors -----------------------------------------');
    }

    property Component monitorInfoComponent: Component {
        MonitorInfo {}
    }

    function destroyOldMonitors() {
        for (var i = 0; i < root.monitors.length; i++) {
            if (root.monitors[i]) {
                root.monitors[i].destroy();
            }
        }
    }

    Process {
        id: monitorProcess
        command: ["hyprctl", "monitors", "all", "-j"]
        running: true
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    var monitorData = JSON.parse(text);
                    var monitorsList = [];

                    for (var i = 0; i < monitorData.length; i++) {
                        var monitorObject = root.monitorInfoComponent.createObject(root, {
                            modelData: monitorData[i]
                        });
                        if (monitorObject) {
                            monitorsList.push(monitorObject);
                        }
                    }

                    root.destroyOldMonitors();
                    root.monitors = monitorsList;
                } catch (e) {
                    console.error("Failed to parse monitor data:", e);
                }
            }
        }
    }

    function loadMonitors() {
        monitorProcess.running = true;
    }

    function applyMonitorConfig(monitor: MonitorInfo) {
        var lua;
        if (monitor.disabled) {
            lua = 'hl.monitor({ output = "' + monitor.name + '", mode = "disable" })';
        } else {
            lua = 'hl.monitor({'
                + ' output = "' + monitor.name + '",'
                + ' mode = "' + monitor.width + 'x' + monitor.height + '@' + monitor.refreshRate + '",'
                + ' position = "' + monitor.x + 'x' + monitor.y + '",'
                + ' scale = ' + monitor.scale + ','
                + ' transform = ' + monitor.transform
                + ' })';
        }
        Quickshell.execDetached(["hyprctl", "eval", lua]);
    }

    function applyAllMonitors(monitorsList: list<MonitorInfo>) {
        monitorsList.forEach(function (monitor) {
            applyMonitorConfig(monitor);
        });
    }

    function generateConfigContent(monitorsList) {
        var config = "-- Monitor configuration\n";
        config += "-- See https://wiki.hypr.land/Configuring/Basics/Monitors/\n\n";
        config += "-- Monitor configuration generated by Quickshell::DisplaySettingsView\n";
        config += "-- Created On: " + new Date().toLocaleString() + "\n\n";
        monitorsList.forEach(function (monitor: MonitorInfo) {
            config += "-- " + monitor.name + " - " + monitor.description + "\n";
            if (monitor.disabled) {
                config += 'hl.monitor({\n';
                config += '    output    = "' + monitor.name + '",\n';
                config += '    mode      = "disable",\n';
                config += '})\n';
            } else {
                config += 'hl.monitor({\n';
                config += '    output    = "' + monitor.name + '",\n';
                config += '    mode      = "' + monitor.width + 'x' + monitor.height + '@' + monitor.refreshRate + '",\n';
                config += '    position  = "' + monitor.x + 'x' + monitor.y + '",\n';
                config += '    scale     = ' + monitor.scale + ',\n';
                config += '    transform = ' + monitor.transform + ',\n';
                config += '})\n';
            }
            config += "\n";
        });
        config += '-- Fallback for any unspecified monitors\n';
        config += 'hl.monitor({\n';
        config += '    output   = "",\n';
        config += '    mode     = "preferred",\n';
        config += '    position = "auto",\n';
        config += '    scale    = 1,\n';
        config += '})\n';
        return config;
    }

    function resetConfiguration() {
        Quickshell.execDetached(["bash", "-c", "cp -f $HOME/.config/hypr/monitors.lua.bak $HOME/.config/hypr/monitors.lua"]);
    }

    function saveConfiguration(monitorsList: list<MonitorInfo>) {
        Quickshell.execDetached(["bash", "-c", "cp -f $HOME/.config/hypr/monitors.lua $HOME/.config/hypr/monitors.lua.bak"]);
        var content = generateConfigContent(monitorsList);
        var cmd = "cat > $HOME/.config/hypr/monitors.lua <<'QSEOF'\n" + content + "QSEOF";
        Quickshell.execDetached(["bash", "-c", cmd]);
    }
}
