pragma Singleton

import Quickshell
import Quickshell.Io

import QtQuick

Singleton {
    id: root

    property list<MonitorInfo> monitors

    Process {
        id: monitorProcess
        command: ["hyprctl", "monitors", "all", "-j"]
        running: true
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    var monitorData = JSON.parse(text);
                    var monitorsList = [];
                    for (var i = 0; i < monitorData.length; i++) {
                        var monitorComponent = Qt.createComponent("MonitorInfo.qml");
                        if (monitorComponent.status === Component.Ready) {
                            var monitorObject = monitorComponent.createObject(root, {
                                modelData: monitorData[i]
                            });
                            monitorsList.push(monitorObject);
                        }
                    }
                    root.monitors = monitorsList;
                } catch (e) {
                    console.error("Failed to parse monitor data:", e);
                }
            }
        }
    }

    function applyMonitorConfig(monitor: MonitorInfo) {
        var cmd = "hyprctl keyword monitor " + monitor.name + ",";
        if (monitor.disabled) {
            cmd += "disable";
        } else {
            cmd += monitor.width + "x" + monitor.height + "@" + monitor.refreshRate + ",";
            cmd += monitor.x + "x" + monitor.y + ",";
            cmd += monitor.scale + ",";
            cmd += "transform, " + monitor.transform;
        }
        Quickshell.execDetached(["bash", "-c", cmd]);
    }

    function applyAllMonitors() {
        monitors.forEach(function (monitor) {
            applyMonitorConfig(monitor);
        });
        loadMonitors();
    }

    function generateConfigContent() {
        var config = "# Monitor configuration generated by Quickshell::DisplaySettingsView\n";
        config += "# Created On: " + new Date().toLocaleString() + "\n\n";
        monitors.forEach(function (monitor: MonitorInfo) {
            config += "# " + monitor.name + " - " + monitor.description + "\n";
            if (monitor.disabled) {
                config += "monitor=" + monitor.name + ",disable\n";
            } else {
                config += "monitor=" + monitor.name + ",";
                config += monitor.width + "x" + monitor.height + "@" + monitor.refreshRate + ",";
                config += monitor.x + "x" + monitor.y + ",";
                config += monitor.scale + ",";
                config += "transform, " + monitor.transform;
                config += "\n";
            }
            config += "\n";
        });
        return config;
    }

    function resetConfiguration() {
        Quickshell.execDetached(["bash", "-c", "cp -f $HOME/.config/hypr/monitors.conf.bak $HOME/.config/hypr/monitors.conf"]);
    }

    function saveConfiguration() {
        Quickshell.execDetached(["bash", "-c", "cp -f $HOME/.config/hypr/monitors.conf $HOME/.config/hypr/monitors.conf.bak"]);
        Quickshell.execDetached(["bash", "-c", "printf " + JSON.stringify(generateConfigContent(monitors)) + " > $HOME/.config/hypr/monitors.conf"]);
    }
}
