pragma Singleton

import Quickshell
import Quickshell.Io

import QtQuick

Singleton {
    id: root

    property list<MonitorInfo> monitors

    function init() {
        console.log('HyprctlMonitors -----------------------------------------');
    }

    property Component monitorInfoComponent: Component {
        MonitorInfo {}
    }

    function destroyOldMonitors() {
        for (var i = 0; i < root.monitors.length; i++) {
            if (root.monitors[i]) {
                root.monitors[i].destroy();
            }
        }
    }

    Process {
        id: monitorProcess
        command: ["hyprctl", "monitors", "all", "-j"]
        running: true
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    var monitorData = JSON.parse(text);
                    var monitorsList = [];

                    for (var i = 0; i < monitorData.length; i++) {
                        var monitorObject = root.monitorInfoComponent.createObject(root, {
                            modelData: monitorData[i]
                        });
                        if (monitorObject) {
                            monitorsList.push(monitorObject);
                        }
                    }

                    root.destroyOldMonitors();
                    root.monitors = monitorsList;
                } catch (e) {
                    console.error("Failed to parse monitor data:", e);
                }
            }
        }
    }

    function loadMonitors() {
        monitorProcess.running = true;
    }

    function applyMonitorConfig(monitor: MonitorInfo) {
        var cmd = "hyprctl keyword monitor " + monitor.name + ",";
        if (monitor.disabled) {
            cmd += "disable";
        } else {
            cmd += monitor.width + "x" + monitor.height + "@" + monitor.refreshRate + ",";
            cmd += monitor.x + "x" + monitor.y + ",";
            cmd += monitor.scale + ",";
            cmd += "transform, " + monitor.transform;
        }
        Quickshell.execDetached(["bash", "-c", cmd]);
    }

    function applyAllMonitors(monitorsList: list<MonitorInfo>) {
        monitorsList.forEach(function (monitor) {
            applyMonitorConfig(monitor);
        });
    }

    function generateConfigContent(monitorsList) {
        var config = "# Monitor configuration generated by Quickshell::DisplaySettingsView\n";
        config += "# Created On: " + new Date().toLocaleString() + "\n\n";
        monitorsList.forEach(function (monitor: MonitorInfo) {
            config += "# " + monitor.name + " - " + monitor.description + "\n";
            if (monitor.disabled) {
                config += "monitor=" + monitor.name + ",disable\n";
            } else {
                config += "monitor=" + monitor.name + ",";
                config += monitor.width + "x" + monitor.height + "@" + monitor.refreshRate + ",";
                config += monitor.x + "x" + monitor.y + ",";
                config += monitor.scale + ",";
                config += "transform, " + monitor.transform;
                config += "\n";
            }
            config += "\n";
        });
        return config;
    }

    function resetConfiguration() {
        Quickshell.execDetached(["bash", "-c", "cp -f $HOME/.config/hypr/monitors.conf.bak $HOME/.config/hypr/monitors.conf"]);
    }

    function saveConfiguration(monitorsList: list<MonitorInfo>) {
        Quickshell.execDetached(["bash", "-c", "cp -f $HOME/.config/hypr/monitors.conf $HOME/.config/hypr/monitors.conf.bak"]);
        Quickshell.execDetached(["bash", "-c", "printf " + JSON.stringify(generateConfigContent(monitorsList)) + " > $HOME/.config/hypr/monitors.conf"]);
    }
}