pragma Singleton

import Quickshell
import Quickshell.Hyprland
import Quickshell.Io

import QtQuick

Singleton {
    id: root

    property var monitors: []
    property bool loading: false

    // Load monitor information from hyprctl
    function loadMonitors() {
        loading = true;
        monitorProcess.running = true;
    }

    Process {
        id: monitorProcess
        command: ["hyprctl", "monitors", "all", "-j"]
        running: false

        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    var monitorData = JSON.parse(text);
                    root.monitors = monitorData.map(function (mon) {
                        return {
                            id: mon.id,
                            name: mon.name,
                            description: mon.description || (mon.make + " " + mon.model),
                            make: mon.make || "",
                            model: mon.model || "",
                            enabled: !mon.disabled,
                            isPrimary: mon.focused,
                            width: mon.width,
                            height: mon.height,
                            resolution: mon.width + "x" + mon.height,
                            refreshRate: Math.round(mon.refreshRate),
                            position: {
                                x: mon.x,
                                y: mon.y
                            },
                            scale: mon.scale || 1.0,
                            transform: mon.transform || 0,
                            rotation: root.transformToRotation(mon.transform || 0),
                            modes: root.parseAvailableModes(mon.availableModes || []),
                            activeWorkspace: (mon.activeWorkspace && mon.activeWorkspace.id) || 1,
                            dpmsStatus: mon.dpmsStatus,
                            vrr: mon.vrr || false,
                            disabled: mon.disabled || false
                        };
                    });
                    root.loading = false;
                } catch (e) {
                    console.error("Failed to parse monitor data:", e);
                    root.loading = false;
                }
            }
        }
    }

    // Convert Hyprland transform value to rotation degrees
    function transformToRotation(transform) {
        switch (transform) {
        case 0:
            return 0;
        case 1:
            return 90;
        case 2:
            return 180;
        case 3:
            return 270;
        default:
            return 0;
        }
    }

    // Convert rotation degrees to Hyprland transform value
    function rotationToTransform(rotation) {
        switch (rotation) {
        case 0:
            return 0;
        case 90:
            return 1;
        case 180:
            return 2;
        case 270:
            return 3;
        default:
            return 0;
        }
    }

    // Parse available modes from the string array
    function parseAvailableModes(modesArray) {
        var modes = [];
        modesArray.forEach(function (modeStr) {
            var match = modeStr.match(/(\d+)x(\d+)@([\d.]+)Hz/);
            if (match) {
                var width = parseInt(match[1]);
                var height = parseInt(match[2]);
                var refresh = Math.round(parseFloat(match[3]));
                modes.push({
                    resolution: width + "x" + height,
                    refreshRate: refresh,
                    width: width,
                    height: height
                });
            }
        });
        return modes;
    }

    // Apply monitor configuration
    function applyMonitorConfig(monitor) {
        var cmd = "keyword monitor " + monitor.name + ",";

        if (!monitor.enabled || monitor.disabled) {
            cmd += "disable";
        } else {
            cmd += monitor.resolution + "@" + monitor.refreshRate + ",";
            cmd += monitor.position.x + "x" + monitor.position.y + ",";
            cmd += monitor.scale;

            if (monitor.rotation !== 0) {
                cmd += ",transform," + rotationToTransform(monitor.rotation);
            }
        }

        console.log("Applying monitor config:", cmd);
        Hyprland.dispatch(cmd);
    }

    // Apply all monitor configurations
    function applyAllMonitors(monitorsArray) {
        monitorsArray.forEach(function (monitor) {
            applyMonitorConfig(monitor);
        });
        // Reload after applying
        Qt.callLater(function () {
            loadMonitors();
        });
    }

    // Generate Hyprland config file content
    function generateConfigContent(monitorsArray) {
        var config = "# Monitor configuration generated by DisplaySettingsView\n";
        config += "# " + new Date().toLocaleString() + "\n\n";

        monitorsArray.forEach(function (monitor) {
            config += "# " + monitor.name + " - " + monitor.description + "\n";

            if (!monitor.enabled || monitor.disabled) {
                config += "monitor=" + monitor.name + ",disable\n";
            } else {
                config += "monitor=" + monitor.name + ",";
                config += monitor.resolution + "@" + monitor.refreshRate + ",";
                config += monitor.position.x + "x" + monitor.position.y + ",";
                config += monitor.scale;

                if (monitor.rotation !== 0) {
                    config += ",transform," + rotationToTransform(monitor.rotation);
                }

                config += "\n";
            }
            config += "\n";
        });

        return config;
    }

    // Save configuration to file
    function saveConfiguration(monitorsArray, configPath) {
        var content = generateConfigContent(monitorsArray);

        // Create a temporary file with the content and move it to the target location
        var tmpFile = "/tmp/quickshell_monitors_" + Date.now() + ".conf";

        // Write content to temp file using printf to avoid shell escaping issues
        Quickshell.execDetached(["bash", "-c", "printf '%s' " + JSON.stringify(content) + " > " + tmpFile + " && mv " + tmpFile + " " + configPath.replace("~", "$HOME")]);

        console.log("Monitor configuration saved to:", configPath);
        return content;
    }

    // Generate workspace assignments
    function generateWorkspaceConfig(workspaceAssignments) {
        var config = "# Workspace assignments generated by DisplaySettingsView\n";
        config += "# " + new Date().toLocaleString() + "\n\n";

        workspaceAssignments.forEach(function (ws) {
            config += "workspace=" + ws.id + ",monitor:" + ws.output + "\n";
        });

        return config;
    }

    // Save workspace configuration
    function saveWorkspaceConfig(workspaceAssignments, configPath) {
        var content = generateWorkspaceConfig(workspaceAssignments);

        // Create a temporary file with the content and move it to the target location
        var tmpFile = "/tmp/quickshell_workspaces_" + Date.now() + ".conf";

        // Write content to temp file using printf to avoid shell escaping issues
        Quickshell.execDetached(["bash", "-c", "printf '%s' " + JSON.stringify(content) + " > " + tmpFile + " && mv " + tmpFile + " " + configPath.replace("~", "$HOME")]);

        console.log("Workspace configuration saved to:", configPath);
        return content;
    }

    Component.onCompleted: {
        loadMonitors();
    }
}
